### ISSUE TITLE
Please make new release before changes in API

### ISSUE THREAD

**Issue by qwerty2586** [jbub/fio#3]
Can you make new release before 30 November 2024. Fio will take down old endpoint? I am using master of library in code right now and api is working. I would just prefer to use release. Thanks.

**Comment by jbub** [comment]
Damn i forgot :D Will do

**Comment by jbub** [comment]
https://github.com/jbub/fio/releases/tag/v0.7.0

**Comment by qwerty2586** [comment]
Cool. Thank you!!!
